### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by jonalange** [HyperCubeMC/old-starline-sodium-fabric#1]
Will there be a 1.18 version (for the experimental snapshots) just like iris? I would love to see that!

**Comment by TrillionDeTurtle** [comment]
I really want to know as well because if you run the starline fork in the experimental snapshot it keeps saying to add the compatible sodium fork if you want to run benchmarks or get higher fps

**Comment by bluejt** [comment]
我也很需要 支撑1.18-21w37a的 钠！

**Comment by Justsnoopy30** [comment]
1.18-starline branch has this
