### ISSUE TITLE
sodium-fabric-mc1.17.1-0.3.0+IRIS2-build.117.jar (latest) crashing with iris-mc1.17-1.1.1.jar (latest)

### ISSUE THREAD

**Issue by Magnuswlange** [HyperCubeMC/old-starline-sodium-fabric#3]
### Version

> sodium-fabric-mc1.17.1-0.3.0+IRIS2-build.117.jar crashing with iris-mc1.17-1.1.1.jar running on fabric-loader-0.11.6-1.17.1.jar

### Reproduction Steps

> Launch game, load world. Loading world -> saving world (because of the crash)
[crash-2021-08-15_22.09.59-client.txt](https://github.com/HyperCubeMC/sodium-fabric/files/6988817/crash-2021-08-15_22.09.59-client.txt)

### Crash Report File

> Attached

**Comment by Magnuswlange** [comment]
New crash report; only those two mods and Fabric API.
[crash-2021-08-15_22.18.53-client.txt](https://github.com/HyperCubeMC/sodium-fabric/files/6988836/crash-2021-08-15_22.18.53-client.txt)

EDIT: just to be sure. I can't run your fork alone, I get an error that it's missing Iris, so I combine this with Iris (which comes with Sodium added), right?

**Comment by Justsnoopy30** [comment]
Closing as lack of activity
