### ISSUE TITLE
Crash on startup with Immersive Portals mod. [1.16.5]

### ISSUE THREAD

**Issue by SierraDT** [HyperCubeMC/old-starline-sodium-fabric#4]
sodium-fabric-mc1.16.5-0.2.0+IRIS3-build.119

1. Install Iris Starline.
2. Install Sodium for Iris Starline.
3. Install Immersive Portals.
4. Launch the game.

[crash-2021-08-21_13.24.23-client.txt](https://github.com/HyperCubeMC/sodium-fabric/files/7025327/crash-2021-08-21_13.24.23-client.txt)

It works without sodium.

**Comment by Justsnoopy30** [comment]
Immersive Portals is incompatible with sodium on 1.16, you will need to use 1.17 for them to be compatible.
