### ISSUE TITLE
[Minecraft 1.17.1] Sodium (Iris Starline fork) will not work with Fabric Loader => 12.x

### ISSUE THREAD

**Issue by NohanMV** [HyperCubeMC/old-starline-sodium-fabric#7]
### Version

sodium-fabric-mc1.17.1-0.3.2+IRIS2-rev.ad603ca.jar

### Reproduction Steps

1. Clone Iris 1.17 Starline fork, build it with JDK16 and use publishToMavenLocal.
2. Clone Sodium 1.17 Starline fork, build it with JDK16.
3. Install the Fabric Mod loader version 12.x
4. Install Sodium into Minecraft with the Fabric api (crash happens with and without Iris).
5. Launch the game.
6. Crash

### Crash Report File

[crash-2021-11-03_16.39.16-client.txt](https://github.com/HyperCubeMC/sodium-fabric/files/7468814/crash-2021-11-03_16.39.16-client.txt)

### Game Log

https://paste.ee/p/dY6Jn

### Additional Information

Minecraft windows opens with a black screen and then quickly closes.
MultiMC 0.6.13-develop-2785
AdoptOpenJDK 16
Arch Linux linux-zen 5.14.16 Gnome on Wayland

**Comment by qualk** [comment]
Can confirm also happening on Windows 11.

**Comment by HeartlessAUS** [comment]
can confirm recent 1.17 build breaks with same error.
rolled back to [Action 1227706253](https://github.com/HyperCubeMC/sodium-fabric/actions/runs/1227706253) and it works fine

**Comment by Mr-Waterscout** [comment]
Yeah, I had the same issue but HearlessAUS's suggestion fixed it.

**Comment by Ascellayn** [comment]
HeartlessAUS's fix also worked for me.

**Comment by Justsnoopy30** [comment]
I'm working on this right now, sorry for the delay.

**Comment by Justsnoopy30** [comment]
Fixed!
