### ISSUE TITLE
[Minecraft 1.18-pre1] Nether and End terrain not rendering in latest build sodium-fabric-mc1.18-pre1-0.3.2+IRIS2-build.169.jar

### ISSUE THREAD

**Issue by RYAN5138** [HyperCubeMC/old-starline-sodium-fabric#8]
### Version Information

sodium-fabric-mc1.18-pre1-0.3.2+IRIS2-build.169.jar

### Expected Behavior

Terrain in Nether and End dimensions should render when entering through portal or entering world.

### Actual Behavior

Terrain doesn't render in Nether or End dimensions. Entities seem to function properly but no blocks/tile entities are visible. Terrain becomes visible again upon entering overworld, but persists in other dimensions even after reloading chunks or exiting and re-entering game.

### Reproduction Steps

Enter Nether or End dimensions in Minecraft 1.18-pre1 with build 169. 

using iris-mc1.18-pre1-1.1.3-starline+build.600.jar with sodium, but problem only appears when sodium is installed. previous  sodium build 168 works perfectly fine.

### System Information

Java Version: 16.0.1 64 bit
CPU: 16x AMD Ryzen 5800x 8-core processor 
GPU: Nvidia Geforce RTX 3080

### Other Information

fabric-api-0.42.2+1.18.jar
iris-mc1.18-pre1-1.1.3-starline+build.600.jar

**Comment by Justsnoopy30** [comment]
Sodium fork is deprecated now, see README
